name: CI-CD - XM Cloud
on: 
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - .github/workflows/CI-CD_XM_Cloud.yml
    - .github/workflows/deploy_xmCloud.yml
    - .github/workflows/build_DotNet.yml
    - 'xmcloud.build.json'
    - 'src/**/platform/**'
    - 'src/**/items/**'
    - 'src/Project/Sugcon2024/**'
    - 'src/Project/Sugcon/**'
  pull_request:
    branches: [ main ]
    paths:
    - .github/workflows/CI-CD_XM_Cloud.yml
    - .github/workflows/deploy_xmCloud.yml
    - .github/workflows/build_DotNet.yml
    - 'xmcloud.build.json'
    - 'src/**/platform/**'
    - 'src/**/items/**'
    - 'src/Project/Sugcon2024/**'
    - 'src/Project/Sugcon/**'

jobs:

  build-dotnet:
    uses: ./.github/workflows/build_DotNet.yml
    with:
      buildConfiguration: Release

  deploy-staging:
    uses: ./.github/workflows/deploy_xmCloud.yml
    needs: build-dotnet 
    with:
      environmentName: Staging
    secrets:
      XM_CLOUD_CLIENT_ID: ${{ secrets.XM_CLOUD_CLIENT_ID }}
      XM_CLOUD_CLIENT_SECRET: ${{ secrets.XM_CLOUD_CLIENT_SECRET }}
      XM_CLOUD_ENVIRONMENT_ID: ${{ secrets.STAGING_XM_CLOUD_ENVIRONMENT_ID }}

  promote-to-prod:
    needs: deploy-staging 
    uses: ./.github/workflows/promote_xmCloud.yml
    with:
      environmentName: Production
      deploymentId: ${{ needs.deploy-staging.outputs.deploymentId }}
    secrets:
      XM_CLOUD_CLIENT_ID: ${{ secrets.XM_CLOUD_CLIENT_ID }}
      XM_CLOUD_CLIENT_SECRET: ${{ secrets.XM_CLOUD_CLIENT_SECRET }}
      XM_CLOUD_ENVIRONMENT_ID: ${{ secrets.PRODUCTION_XM_CLOUD_ENVIRONMENT_ID }} 
