name: Deploy the solution and items to an XM Cloud instance

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string
    outputs:
      completedDeploymentId:
        value: '${{ jobs.deploy.outputs.completedDeploymentId }}'
    secrets:
      XM_CLOUD_CLIENT_ID:
        required: true
      XM_CLOUD_CLIENT_SECRET:
        required: true
      XM_CLOUD_ENVIRONMENT_ID:
        required: true  
    
jobs:

  deploy:
    name: Deploy the XM Cloud ${{ inputs.environmentName }} Site
    runs-on: ubuntu-latest
    outputs:
      completedDeploymentId: ${{ steps.run-deployment.outputs.completedDeploymentId }}
    steps:
    - name: Deploy the CM assets to XM Cloud
      id: run-deployment
      run: |
        echo "completedDeploymentId=HelloWorld" >> $GITHUB_OUTPUT